name: Terraform Deployment Troubleshoot
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TF_CLOUD_ORGANIZATION: "TFG-IPAM"
  TF_WORKSPACE: "tfg-multi-repo"
  AWS_REGION: "us-west-2"

jobs:
  terraform-troubleshoot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        terraform_version: 1.5.7

    - name: Create Terraform CLI Config
      run: |
        mkdir -p ~/.terraform.d
        cat << EOF > ~/.terraformrc
        credentials "app.terraform.io" {
          token = "${{ secrets.TF_API_TOKEN }}"
        }
        EOF
        cat ~/.terraformrc

    - name: Troubleshoot Terraform Initialization
      run: |
        echo "Terraform version:"
        terraform version

        echo "Listing Terraform providers:"
        terraform providers

        echo "Attempting to initialize with verbose debugging:"
        TF_LOG=TRACE terraform init -backend=true -reconfigure -force-copy 

    - name: Display Terraform Logs
      if: failure()
      run: |
        cat terraform.log || echo "No terraform log found"
